
// State and county mapping for jurisdictions
export const stateCountiesMap: Record<string, string[]> = {
  "Alabama": ["Baldwin", "Jefferson", "Madison", "Mobile", "Montgomery"],
  "Alaska": ["Anchorage", "Fairbanks North Star", "Juneau", "Matanuska-Susitna"],
  "Arizona": ["Maricopa", "Pima", "Pinal", "Yavapai", "Yuma"],
  "Arkansas": ["Benton", "Pulaski", "Sebastian", "Washington"],
  "California": ["Alameda", "Los Angeles", "Orange", "Riverside", "Sacramento", "San Bernardino", "San Diego", "San Francisco", "Santa Clara", "Ventura"],
  "Colorado": ["Adams", "Arapahoe", "Boulder", "Denver", "El Paso", "Jefferson", "Larimer"],
  "Connecticut": ["Fairfield", "Hartford", "New Haven", "New London"],
  "Delaware": ["Kent", "New Castle", "Sussex"],
  "Florida": ["Broward", "Duval", "Hillsborough", "Miami-Dade", "Orange", "Palm Beach", "Pinellas", "Polk"],
  "Georgia": ["Cobb", "DeKalb", "Fulton", "Gwinnett", "Richmond"],
  "Hawaii": ["Hawaii", "Honolulu", "Kauai", "Maui"],
  "Idaho": ["Ada", "Canyon", "Kootenai"],
  "Illinois": ["Cook", "DuPage", "Kane", "Lake", "Will"],
  "Indiana": ["Allen", "Lake", "Marion", "St. Joseph", "Vanderburgh"],
  "Iowa": ["Linn", "Polk", "Scott", "Woodbury"],
  "Kansas": ["Johnson", "Sedgwick", "Shawnee", "Wyandotte"],
  "Kentucky": ["Fayette", "Jefferson", "Kenton"],
  "Louisiana": ["Caddo", "East Baton Rouge", "Jefferson", "Orleans"],
  "Maine": ["Cumberland", "Penobscot", "York"],
  "Maryland": ["Anne Arundel", "Baltimore", "Montgomery", "Prince George's"],
  "Massachusetts": ["Essex", "Middlesex", "Norfolk", "Suffolk", "Worcester"],
  "Michigan": ["Genesee", "Ingham", "Kent", "Macomb", "Oakland", "Wayne"],
  "Minnesota": ["Anoka", "Dakota", "Hennepin", "Ramsey", "St. Louis"],
  "Mississippi": ["DeSoto", "Harrison", "Hinds", "Jackson"],
  "Missouri": ["Greene", "Jackson", "St. Charles", "St. Louis"],
  "Montana": ["Cascade", "Flathead", "Gallatin", "Missoula", "Yellowstone"],
  "Nebraska": ["Douglas", "Lancaster", "Sarpy"],
  "Nevada": ["Clark", "Washoe"],
  "New Hampshire": ["Hillsborough", "Merrimack", "Rockingham", "Strafford"],
  "New Jersey": ["Bergen", "Essex", "Hudson", "Middlesex", "Monmouth", "Ocean", "Passaic"],
  "New Mexico": ["Bernalillo", "Doña Ana", "Sandoval", "Santa Fe"],
  "New York": ["Albany", "Bronx", "Kings (Brooklyn)", "Nassau", "New York (Manhattan)", "Queens", "Richmond (Staten Island)", "Suffolk", "Westchester"],
  "North Carolina": ["Forsyth", "Guilford", "Mecklenburg", "Wake"],
  "North Dakota": ["Burleigh", "Cass", "Grand Forks"],
  "Ohio": ["Cuyahoga", "Franklin", "Hamilton", "Lucas", "Montgomery", "Summit"],
  "Oklahoma": ["Cleveland", "Oklahoma", "Tulsa"],
  "Oregon": ["Clackamas", "Lane", "Marion", "Multnomah", "Washington"],
  "Pennsylvania": ["Allegheny", "Bucks", "Chester", "Delaware", "Montgomery", "Philadelphia"],
  "Rhode Island": ["Kent", "Newport", "Providence", "Washington"],
  "South Carolina": ["Charleston", "Greenville", "Horry", "Richland", "Spartanburg"],
  "South Dakota": ["Minnehaha", "Pennington"],
  "Tennessee": ["Davidson", "Hamilton", "Knox", "Shelby"],
  "Texas": ["Bexar", "Collin", "Dallas", "Denton", "El Paso", "Fort Bend", "Harris", "Hidalgo", "Tarrant", "Travis"],
  "Utah": ["Davis", "Salt Lake", "Utah", "Weber"],
  "Vermont": ["Chittenden", "Rutland", "Washington", "Windham"],
  "Virginia": ["Arlington", "Chesterfield", "Fairfax", "Henrico", "Loudoun", "Prince William", "Virginia Beach"],
  "Washington": ["King", "Pierce", "Snohomish", "Spokane", "Thurston"],
  "West Virginia": ["Berkeley", "Cabell", "Kanawha", "Monongalia"],
  "Wisconsin": ["Brown", "Dane", "Milwaukee", "Racine", "Waukesha"],
  "Wyoming": ["Laramie", "Natrona"],
  "District of Columbia": ["Washington DC"],
  "Federal": ["Northern District", "Southern District", "Eastern District", "Western District", "Central District"],
};

export const states = [
  "Alabama", 
  "Alaska", 
  "Arizona", 
  "Arkansas", 
  "California", 
  "Colorado", 
  "Connecticut", 
  "Delaware", 
  "Florida", 
  "Georgia", 
  "Hawaii", 
  "Idaho", 
  "Illinois", 
  "Indiana", 
  "Iowa", 
  "Kansas", 
  "Kentucky", 
  "Louisiana", 
  "Maine", 
  "Maryland", 
  "Massachusetts", 
  "Michigan", 
  "Minnesota", 
  "Mississippi", 
  "Missouri", 
  "Montana", 
  "Nebraska", 
  "Nevada", 
  "New Hampshire", 
  "New Jersey", 
  "New Mexico", 
  "New York", 
  "North Carolina", 
  "North Dakota", 
  "Ohio", 
  "Oklahoma", 
  "Oregon", 
  "Pennsylvania", 
  "Rhode Island", 
  "South Carolina", 
  "South Dakota", 
  "Tennessee", 
  "Texas", 
  "Utah", 
  "Vermont", 
  "Virginia", 
  "Washington", 
  "West Virginia", 
  "Wisconsin", 
  "Wyoming", 
  "District of Columbia",
  "Federal",
  "Other"
];

export const caseTypes = [
  "Contract Dispute",
  "Negligence",
  "Civil Rights",
  "Injury",
  "Family Law",
  "Property Law",
  "Business/Commercial Law",
  "Employment Law",
  "Intellectual Property",
  "Probate",
  "Tort Law"
];

export const caseStages = [
  "Assessing filing",
  "Filing",
  "Discovery",
  "Pre-Trial",
  "Trial",
  "Post-Trial",
  "Appeal",
  "Settlement",
  "Closed"
];
